# Generated by Django 2.1.5 on 2019-02-22 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190222_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 18, 52, 8, 683036, tzinfo=utc), verbose_name='date published'),
        ),
    ]
